title: "Mentorship Resources - Turing School of Software and Design"
description: "Open source mentorship resources for the Turing School of Software and Design"
url: "https://mentorship.turing.io/"

baseurl: '/'
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

gems:
  - jemoji
